# conf/config.yaml
# 默认为True, 控制台打印消息
debug: true

# 日志保留天数
log_days: 3

# 指定进程数
process_num: 4

# 宠汪汪进程数
joy_process_num: 1

jd_cookies:
  - pt_pin=;pt_key=;
  - pt_pin=;pt_key=;
  - pt_pin=;pt_key=;
# 东东农场是否使用水滴换豆卡, 100水滴换20京豆
jd_farm_bean_card: false

# 东东农场每天保留多少水滴, 用于明天的十次浇水任务
jd_farm_retain_water: 80

# 消息通知
notify:
  # TG机器人Token
  tg_bot_token: aaa
  # TG用户ID
  tg_user_id: bbb
  # push+ token: https://pushplus.hxtrip.com/
  push_p_token: null

# 是否开启京豆夺宝功能
jd_bean_indiana: true
