name: dj_fruit

on:
    workflow_dispatch:
    schedule:
        - cron: "1 2,13 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: dj_fruit

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            #- uses: actions/checkout@v1
            
                  
            - name: 'Set up Python'
              uses: actions/setup-python@v1
              with:
                python-version: 3.7
         
            
                  
            - name: run
              run: |
                  
                  
                  
                  pip install virtualenv
                  virtualenv venv && source ./venv/bin/activate
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  
                  sed -i '15c/${{ secrets.JD_COOKIE1 }}' config.yaml
                  sed -i '16c/${{ secrets.JD_COOKIE2 }}' config.yaml
                  sed -i '17c/${{ secrets.JD_COOKIE3 }}' config.yaml
                  sed -i "s#pt_pin#  - pt_pin#g" config.yaml
                  mkdir conf 
                  cp config.yaml conf/config.yaml        
                  cat conf/config.yaml
                  #python dj_fruit.py
                  
