name: dj_fruit

on:
    workflow_dispatch:
    schedule:
        - cron: "1 2,13 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: dj_fruit

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            #- uses: actions/checkout@v1
            
                  
            - name: 'Set up Python'
              uses: actions/setup-python@v1
              with:
                python-version: 3.7
         
            
                  
            - name: run
              run: |
                  
                  git clone https://github.com/wudongdefeng/jd_py.git ~/jdpy
                  cd ~/jdpy
                  pip install virtualenv
                  virtualenv venv && source ./venv/bin/activate
                  pip3 install -r requirements.txt
                  sed -i "15c/${{ secrets.JD_COOKIE1 }}" config.yaml
                  sed -i "16c/${{ secrets.JD_COOKIE2 }}" config.yaml
                  sed -i "17c/${{ secrets.JD_COOKIE3 }}" config.yaml
                  sed -i "s@#pt@#  - pt@#g" config.yaml
                  mkdir conf 
                  cp ~/jdpy/config.yaml ~/jdpy/conf/config.yaml        
                  
                  python dj_fruit.py
                  
