name: test-cookie

on:
    workflow_dispatch:
       
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2            
            
                  
          - name: runs
            run: |                         
                sed -i -e '/pt/d' ./config.yaml
                cat ./config.yaml
      
                sed -i "15c${{ secrets.TEST_COOKIE }}" ./config.yaml
                sed -i "s/pt_key/  - pt_key/g" ./config.yaml
                
   
                cat ./config.yaml
                sed 's/&/\n/g' ./config.yaml
             
                
                cat ./config.yaml
                
                cat ./config.yaml
