name: test

on:
    workflow_dispatch:
    schedule:
        - cron: "45 23,4,11 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: test

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2            
            
                  
          - name: Delete workflow runs
            uses: Mattraks/delete-workflow-runs@main
            with:
              token: ${{ secrets.USER_TOKEN }}
              repository: ${{ github.repository }}
              retain_days: 1
          - name: RUNS
            run:
                 curl -X POST "https://api.telegram.org/bot${{ secrets.TG_USER_ID }}\:${{ secrets.TG_BOT_TOKEN }}/sendMessage" -d "chat_id=-1001401411583&text=py已更新
