name: test-cookie

on:
    workflow_dispatch:
       
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2            
            
                  
          - name: runs
            run: |                         
                pip install -r requirements.txt
                
                sed -i -e '/pt/d' ./config.yaml                    
                sed -i "15c${{ secrets.TEST_COOKIE }}" ./config.yaml
                sed 's/&/\n/g' ./config.yaml               
                sed -i "/pt_key/&  - /g"  ./config.yaml                               
                mkdir conf 
                mv ./config.yaml ./conf/config.yaml
                py jd_bean_change.py
                
                
