name: test-cookie

on:
    workflow_dispatch:
       
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
          - name: Checkout
            uses: actions/checkout@v2            
            
                  
          - name: runs
            run: |                         
                echo "pt_key=aaa;pt_pin=bbb;&pt_key=aaa;pt_pin=bbb;" | sed 's/&/\n/g'
                sed -i "15c#${{ secrets.TEST_COOKIE }}" ./config.yaml
                sed 's/&/\n/g' ./config.yaml
                sed -i "15,17s/^/  - /g" ./config.yaml

                cat ./config.yaml

